### ISSUE TITLE
cant start on 1.12.2 java 21

### ISSUE THREAD

**Issue by Fjox** [KoxSosen/SimpleVoiceBans#2]
```[23:48:28 INFO]: [SimpleVoiceBans] Enabling SimpleVoiceBans v1.0-SNAPSHOT
[23:48:28 INFO]: [SimpleVoiceBans] Successfully registered!
[23:48:28 INFO]: [SimpleVoiceBans] We determined that you do not have LibertyBans installed on this backend server.
[23:48:28 INFO]: [SimpleVoiceBans] Therefore we assume that you have it installed on the proxy.
[23:48:28 INFO]: [SimpleVoiceBans] Enabling proxy support.
[23:48:28 INFO]: [SimpleVoiceBans] This server is proxied.
[23:48:28 ERROR]: Error occurred while enabling SimpleVoiceBans v1.0-SNAPSHOT (Is it up to date?)
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 20 chars (attempted 22 - 'simplevoicebans:custom.
        at org.bukkit.plugin.messaging.StandardMessenger.validateChannel(StandardMessenger.java:446) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.messaging.StandardMessenger.registerOutgoingPluginChannel(StandardMessenger.java:179) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.github.koxsosen.bukkit.BukkitPluginLoader.onEnable(BukkitPluginLoader.java:56) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:1583) [?:?]```

**Comment by KoxSosen** [comment]
Thank you! I'll push out a fix in the coming days.

**Comment by Fjox** [comment]
when this happends and someone talks on the server it spams this error ```[01:02:53 ERROR]: [voicechat] Failed to dispatch event 'MicrophonePacketEvent'
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:488) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:168) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:142) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:125) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.github.koxsosen.bukkit.SimpleVoiceBans.onMicrophone(SimpleVoiceBans.java:73) ~[?:?]
        at de.maxhenkel.voicechat.plugins.PluginManager.dispatchEvent(PluginManager.java:139) ~[?:?]
        at de.maxhenkel.voicechat.plugins.PluginManager.onMicPacket(PluginManager.java:242) ~[?:?]
        at de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:302) ~[?:?]
        at de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:269) ~[?:?]```

**Comment by KoxSosen** [comment]
Untested fix is available on the fix-older-compatibility branch. If you can compile plugins, feel free to give it a try, otherwise I'll release a version that is verified to work on 1.12 in a couple days.

**Comment by Fjox** [comment]
> Untested fix is available on the fix-older-compatibility branch. If you can compile plugins, feel free to give it a try, otherwise I'll release a version that is verified to work on 1.12 in a couple days.

its gradle, anyone can compile gradle. its not gcc

**Comment by Fjox** [comment]
did gradle change or since when do i need to type a project name for it to compile?

**Comment by KoxSosen** [comment]
SimpleVoiceBans uses a multi-module gradle build system, so we have multiple modules for each platform, and a common module for shared methods. So make sure that you are executing the `uberJar` task in the root "parent" module to get a working jar for every platform. Jars will be in `<platform-name>/build/SimpleVoiceBans-<version>-uber.jar`.

**Comment by Fjox** [comment]
> Untested fix is available on the fix-older-compatibility branch. If you can compile plugins, feel free to give it a try, otherwise I'll release a version that is verified to work on 1.12 in a couple days.


```[01:17:03 ERROR]: Could not load 'plugins/SimpleVoiceBans-SimpleVoiceBans-1.3-SNAPSHOT-uber.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more```

**Comment by Fjox** [comment]
> SimpleVoiceBans uses a multi-module gradle build system, so we have multiple modules for each platform, and a common module for shared methods. So make sure that you are executing the `uberJar` task in the root "parent" module to get a working jar for every platform. Jars will be in `<platform-name>/build/SimpleVoiceBans-<version>-uber.jar`.

oh sorry i compiled it with only uber bruh

**Comment by Fjox** [comment]
nvm same error
```[01:22:48 ERROR]: Could not load 'plugins/SimpleVoiceBans-SimpleVoiceBans-1.3-SNAPSHOT-uber.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more```

**Comment by KoxSosen** [comment]
Are you sure you are using the right jar? Which commands did you execute in which directories?

**Comment by Fjox** [comment]
> Are you sure you are using the right jar? Which commands did you execute in which directories?

gradlew uberJar in C:\Users\Fox Ritch\Downloads\SimpleVoiceBans-fix-older-compatibility\

**Comment by KoxSosen** [comment]
That sounds correct. And which jars did you move to the server?

**Comment by Fjox** [comment]
the only jar i could find in /build

also can we move to discord?

**Comment by KoxSosen** [comment]
Sure, you can add me as `koxsosen`.

**Comment by KoxSosen** [comment]
Thank you for reporting again! A fix has been merged, release will be out soon.
