### ISSUE TITLE
Doesnt work on java8

### ISSUE THREAD

**Issue by Fjox** [KoxSosen/SimpleVoiceBans#3]

**Comment by KoxSosen** [comment]
Would you be able to share a stack trace? That would be really helpful in terms of resolving the conflicts.

**Comment by Fjox** [comment]
> Would you be able to share a stack trace? That would be really helpful in terms of resolving the conflicts.

i didnt send it because its just the generic file was compiled with newer java
``` 
[23:49:41 ERROR]: Could not load 'plugins/SimpleVoiceBans-bukkit-1.2-uber.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/github/koxsosen/bukkit/BukkitPluginLoader has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.UnsupportedClassVersionError: com/github/koxsosen/bukkit/BukkitPluginLoader has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_312]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_312]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_312]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_312]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_312]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_312]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_312]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_312]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 6 more```

**Comment by KoxSosen** [comment]
Got it, thank you! This will be fixed as well in the upcoming release.

**Comment by Fjox** [comment]
Made a fork that runs on java8: https://github.com/Foxtanium/SimpleVoiceBans-Java8
